### ISSUE TITLE
save_image unsupported operation

### ISSUE THREAD

**Issue by Timmmm** [arrayfire/arrayfire-rust#115]
Maybe I'm using it wrong (thought it's hard to tell because there's not really any documentation), but `save_image()` always gives me this error:

    thread 'main' panicked at 'Error message: Unsupported operation/parameter option', C:\Users\Tim\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.2\src\error.rs:66

I've tried PNG, JPEG, f32 arrays, u8, 3D, 2D, etc. It really needs better error reporting too.

**Comment by 9prady9** [comment]
Can please share the code stub that can help me reproduce the issue. Also, please do `export AF_PRINT_ERRORS=1` from command line and then run the program to see a more detailed error message.

**Comment by Timmmm** [comment]
Here's a fairly minimal test case:

```
extern crate arrayfire as af;

use af::*;

fn main() {
	set_device(0);
	info();

	let win = Window::new(100, 100, "Test".to_string());

	let values = [0u8, 0];
	let mat = Array::new(&values, Dim4::new(&[2, 1, 1, 1]));

	let mut it: i32 = 0;
	while !win.is_closed() {

		win.draw_image(&mat, None);
		save_image(format!("image_{}.png", it), &mat);

		it += 1;
		if it > 20 {
			break;
		}
	}
}
```

What's weird is that sometimes it creates between 1 and 5 images and then fails. Here's the output:

```
ArrayFire v3.4.1 (CUDA, 64-bit Windows, build b9055b1)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GTX 970, 4096 MB, CUDA Compute 5.2
In function af_err __cdecl af_save_image(const char *,void *const )
In file src\api\c\imageio.cpp:297
FreeImage Error: Unknown Filetype

thread 'main' panicked at 'Error message: Unsupported operation/parameter option', C:\Users\Tim\.cargo\registry\src\github.com-1ecc6299db9ec823\arrayfire-3.4.2\src\error.rs:66
note: Run with `RUST_BACKTRACE=1` for a backtrace.
CUDA Error (30): unknown error
```

That makes it seem like it doesn't support PNG, but it has actually created valid PNG files occasionally so that can't be true. Anyway, trying `.jpg` gives the same error, but again it actually creates a few jpegs. It seems to reliably create 3 for me, and they seem to be valid.

**Comment by Timmmm** [comment]
I wonder if this line is safe:

        let err_val = af_save_image(filename.clone().as_bytes().as_ptr() as *const u8,

Is there a risk the temporary created by `.clone()` is destroyed before `af_save_image()` is called?

**Comment by 9prady9** [comment]
Good catch. While we corrected this issue in all the other modules, somehow image module was not corrected. The root cause is that when we transfer a string to C-FFI, we need to build a CString from String instead of clone and then pass it on to FFI. I am fixed this in devel.

**Comment by Timmmm** [comment]
Awesome, works like a charm. I still can't work out exactly what to `save_image()` so I don't just get a black image but `save_image_native("foo.tif", ...)` with an `f32` array worked perfectly.

Can you explain to an unlearned Rustacean what exactly was wrong with the original code?

**Comment by 9prady9** [comment]
There is a difference in how rust represents the strings using `std::ffi::Cstring` and `std::string::String`.

### std::ffi::CString
```
A type representing an owned C-compatible string

This type serves the primary purpose of being able to safely generate a
C-compatible string from a Rust byte slice or vector. An instance of this
type is a static guarantee that the underlying bytes contain no interior 0
bytes and the final byte is 0.
```

where as 
### std::string::String
```
A UTF-8 encoded, growable string and it stores the underlying data in the
form of vec<u8>. Also, there is no guarantee of having the final 0-byte that
is expected by the C `const char*` strings.
```

This was the issue we fixed.
